#!/usr/bin/env sh

# This is a more reliable way to get the project root
PROJECT_ROOT="$(git rev-parse --show-toplevel)"

# Use project-local commitlint
${PROJECT_ROOT}/node_modules/.bin/commitlint --edit $1 